### ISSUE TITLE
more handy back-ends

### ISSUE THREAD

**Issue by edvorg** [szermatt/emacs-bash-completion#10]
Hi.
Maybe implement something like auto-complete and company backends for this functionality?

**Comment by szermatt** [comment]
The latest version of bash-completion is a completion backend already; it doesn't do the completion on its own but rather returns a list of candidates. I'd expect that all it'd take is to write some adapter to make it work as backend for company or auto-complete. 

Such adapters might even already exist, since anything that supports defuns written for shell-dynamic-complete-functions will accept bash-completion-dynamic-complete. 

Would you care to give it a try?

**Comment by edvorg** [comment]
![screen shot 2015-03-27 at 9 38 21 am](https://cloud.githubusercontent.com/assets/1499595/6861720/c7c18fde-d45c-11e4-9d2e-8b59ae20133b.png)

Sorry. Yes. It already works. I just enabled company mode in shell. Amazing.
Thank you for such a great package.
