### ISSUE TITLE
Add option to suppress "Bash completion..."

### ISSUE THREAD

**Issue by Yevgnen** [szermatt/emacs-bash-completion#12]
The message [here](https://github.com/szermatt/emacs-bash-completion/blob/master/bash-completion.el#L314) is just a bit annoying.

**Comment by szermatt** [comment]
Bash sometimes takes a while to start, depending on your machine and configuration. When it takes a long time, it might look like everything's frozen, so it's useful to display something to make it clear that something is going on. 

It would work better if the message were displayed only after a certain times - and make it configurable so that if you set it to a *very* long time, you'll never see the message again.

**Comment by szermatt** [comment]
318e32979fab4e1fcb4fdf400af0e30148544951 introduces an option to control the appearance of that message:

bash-completion-message-delay now controls when an whether the message
"Bash Completion..." is displayed:
 - if it a number, only display it if completion takes longer than
 that much time, in seconds.
 - if it is 0, always display it
 - if it is nil, never display it

The default is to display it if completion takes longer than 400ms.
