### ISSUE TITLE
suggestion for custom functions

### ISSUE THREAD

**Issue by malijani** [szermatt/emacs-bash-completion#38]
**thank's for good work!** <3
![image](https://user-images.githubusercontent.com/40851133/60370315-94023080-9a0b-11e9-87bd-f5f7bdef4f80.png)
there's no suggestion for my written functions (as you can see in the picture) but i can access to my variables in suggestions... how can i fix it? did you Developed any option for this?

**Comment by szermatt** [comment]
montag451 fixed this. Set:

```
 (setq bash-completion-use-separate-processes nil)
```

The root of the problem was that bash-completion.el ran in two different processes, so any functions you added in the current process wasn't seen in the completion process. It was tricky to change, but now, with bash-completion-use-separate-processes, there's only one process.
