### ISSUE TITLE
does not complete sub-sub-commands

### ISSUE THREAD

**Issue by malcook** [szermatt/emacs-bash-completion#6]
for example,  the `environment modules` package defines a bash `module` which has  subcommands as completions, including `use`, which has as sub-completions the list of available packages.  Using emacs-bash-completion, the subcommands are presented as completions, but, upon chosing 'use', the available packages are not presented as completions.

**Comment by szermatt** [comment]
This is an old bug, probably not relevant anymore. 

Sub-commands work, in general, for example with systemctl. What might not work might be  completion for *specific commands* due to differences in behavior between bash completion and bash-completion.el 

If a command or sub-command doesn't work, please open a bug with the details of the command, the script that configures the completion for bash and their versions so I can reproduce.
