### ISSUE TITLE
Help macOS

### ISSUE THREAD

**Issue by aadcg** [szermatt/emacs-bash-completion#69]
I have been using this amazing package for years on Linux, but I'm not able to make work on macOS with the same configuration. It invariably reports `"No match"`. Please see the report below. Any idea? Thanks!

### macOS

```log
commandline: <<EOF
if type __ebcpre &>/dev/null; then   __ebcpre; __ebcompgen -b -c -a -A function -- pw; else   echo ==emacs==nopre=${BASH_VERSION}==.;   __ebcp=("$PS1" "$PROMPT_COMMAND");  unset PS1 PROMPT_COMMAND;fi;
EOF

status: 0
process: #<process shell>
output-buffer: <<EOF
EOF

emacs-version: "29.2"
bash-version: "5.2.26(1)-release"
bash-version: "5.2.26(1)-release"
context: #s(completion "pw"
              ("pw")
              0 "pw" 92 "pw" nil nil "" nil)

```

### Linux

```log
commandline: <<EOF
if type __ebcpre &>/dev/null; then __ebcpre; __ebcompgen -b -c -a -A function -- pw; else echo ==emacs==nopre=${BASH_VERSION}==.; fi;
EOF

status: 0
process: #<process shell>
output-buffer: <<EOF
pwd
pwd
pwdx
pwd
pwck
pwconv
pwunconv
pwd
EOF

emacs-version: "29.1"
bash-version: "5.1.16(1)-release"
bash-version: "5.1.16(1)-release"
context: #s(completion "pw"
              ("pw")
              0 "pw" 6860 "pw" nil nil "\"'><=;|&(:" nil)
```

**Comment by szermatt** [comment]
I'm not sure what could be happening, here. There isn't much information. I know it works on macos, generally, because I primarily use it on a mac. I'll try and reproduce the issue with the specific combination of Emacs and Bash you have, to see whether it's a version issue. 

In the meantime, could you try turning off all customization in Bash and Emacs? Something in the configuration could be triggering some version-specific or OS-specific issue, even if the configuration is the same in both cases. 

Another thing that would be useful for you to try would be to set bash-completion-use-separate-processes to t, using `M-x customize bash-completion-use-separate-processes`. I'm not recommending you always use bash completion that way. Knowing whether this works or not would help me figure out where the problem comes from.
